kumuluzee:
  name: basketball-videos
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/VideosDS
      connection-url: jdbc:postgresql://pg-events.clvqrwayazxs.eu-central-1.rds.amazonaws.com/videos
      username: postgres
      password: postgres12
      pool:
        max-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/VideosDS
    metrics:
      web-instrumentation:
        - name: videos-endpoint
          url-pattern: /v1/videos/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="906c451a-bc58-4cb6-8145-6a2d768e120b-ls.logit.io"
                                  port="26828" protocol="UDP">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="info" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: videos-api
        url: http://localhost:8081/v1
        read-timeout: 5000
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    cluster: 1
    etcd:
      hosts: http://localhost:2379
    ttl: 100
    ping-interval: 5
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET,POST,HEAD,OPTIONS,PUT,DELETE"

rest-config:
  maintenance-mode: false
  api-token: htn12kss3
  string-property: Monday
  boolean-property: false
  integer-property: 23