apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-videos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-videos
  template:
    metadata:
      labels:
        app: basketball-videos
    spec:
      containers:
        - image: lgaljo/rt_basketball_videos:latest
          name: basketball-videos
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
#            - name: KUMULUZEE_SERVER_BASEURL
#              value: http://52.226.192.49/videos
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com/jcjcrytq
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: jcjcrytq
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass-videos
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 60
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: basketball-videos
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: basketball-videos